<a href="https://colab.research.google.com/github/cmannnn/practical_deep_learning_for_coders/blob/main/fast_ai_ch_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ch 2 Questions

-   Provide an example of where the bear classification model might work poorly in production, due to structural or style differences in the training data.

If the quality of the data (resolution) isn't great , the model could be less effective. The model is only as good as the data you provide it.


- Where do text models currently have a major deficiency?

They are good at classification and generating realistic and comprehensive sentences (replies to social media, imitiating authors style, etc.)  but not great at generating correct responses (industry specifc, technical, etc.)

- What are possible negative societal implications of text generation models?

Possible negative implications could be generating hate speech on social media platforms, or if correct sounding information is provided that actually isn't accurate could be harmful for spreading fake news.


- In situations where a model might make mistakes, and those mistakes could be harmful, what is a good alternative to automating a process?

Incorporating the model into a system with human user interaction to simplify work, reduce workload, etc. 

- What kind of tabular data is deep learning particularly good at?

Good at increasing the variety of data that can be used and columns with high number of discrete choices.

- What's a key downside of directly using a deep learning model for recommendation systems?

Deep learning models generally take longer to train than random forests or gradient boosting machines. 

- What are the steps of the Drivetrain Approach?

Defining the objective -> Levers (what inputs can we control?) -> Data (what data can we collect?) -> Models (how the levers influence the objective)

- How do the steps of the Drivetrain Approach map to a recommendation system?

Objective: to drive additional sales by suprising and delighting the cusomter with recommendations of items they would not have purchased without the recommendation.

Lever: the ranking of the recommendations.

Data: new data must be collected to generate recommendations that will cause new sales

Models: could build 2 models for purchase probabilities, conditional on seeing or not seeing a recommendation

- Create an image recognition model using data you curate, and deploy it on the web.

Deployed! (see Github)

- What is DataLoaders?

DataLoaders is a simple class that allows you to access your data through train and valid sets created by the class.

- What four things do we need to tell fastai to create DataLoaders?

The DataLoaders class needs to know: 
- the type of data that is being passed
- how to get the data
- how to label the data
- how to create the validation set

- What does the splitter parameter to DataBlock do?

How to split the data, how much to data to leave out for the validation set, sets the seed



13. How do we ensure a random split always gives the same validation set?

By setting the seed.

- What letters are often used to signify the independent and dependent variables?

x and y

- What's the difference between the crop, pad, and squish resize approaches? When might you choose one over the others?

The crop resize approach slices the image to fit the desired size. The pad approach adds black pixels to the images that are smaller than the desired size which will allows them to fit the desired size. 

- What is data augmentation? Why is it needed?

Data augumentation is when a image is modified without losing the "meaning" of the image in order for the model to better learn about different features. It is needed if the amount of data is small and the model needs extra inputs.  

- What is the difference between item_tfms and batch_tfms?

item_tfms tells the model to add a transformation on one image at a time. batch_tfms tells the model to add a transformation to all of the images at once.

- What is a confusion matrix?

A confusion matrix is a visualization of the number of correct and incorrectly labeled images. Numbers on the diagonal are correct labels, all numbers in other places are incorrect.

- What does export save?

Export saves the model for future use. It can then be used right away to predict other images instead of having to build and train a whole new model.

- What is it called when we use a model for getting predictions, instead of training?

An inference is when a model is getting predictions rather than just training.

- What are IPython widgets?

iPython widgets are GUI components (buttons, calendars, switches, etc.) that can be used in a Colab notebook to add funtionality to your project.

- When might you want to use CPU for deployment? When might GPU be better?

You might want to use a CPU for deployment when there is not a lot of parallel processing that needs to take place. Image recognition such as the bear classifier is an example of image recognition that wouldn't need a GPU. A GPU would be better for live feed recognition where continuous of frames must be ran at the same time.

- What are the downsides of deploying your app to a server, instead of to a client (or edge) device such as a phone or PC?

The dowsides of deploying an app to a server are that it will require a network connection and some latency issues if there are many calls to the model. There could also be privacy issues if the server is not local.

- What are three examples of problems that could occur when rolling out a bear warning system in practice?

Night time images, blurry images, images of strange bear angles, images where bears are not fully in sight of the camera.

- What is "out-of-domain data"?

Data that a model has not seen in training that it is being asked to predict.

- What is "domain shift"?

Where data the model is predicting on, changes over time.

- What are the three steps in the deployment process?

-Manual process: running the model in parallel, humans checking all predictions.

-Limited scope deployment: careful human supervision, time/geography limited.

-Gradual expansion: good reporting system, consider situations where model could go wrong.

#Ch 3 Questions

- Does ethics provide a list of "right answers"?

No, ethcis does not provide a list of "right answers". Ethics is a very complicated issue and can be different in every case. 

- How can working with people of different backgrounds help when considering ethical questions?

Working with people of different backgrounds can help when considering ethical questions because they may notice or point something out that you may have missed. This way, the other groups of people are considered.

- What was the role of IBM in Nazi Germany? Why did the company participate as it did? Why did the workers participate?

IBM helped keep records on Jews that are and would be executed. IBM as a company participated due to increasing profits. Individual workers participated because they were just following orders and didn't seem like it was blood on their hands.

- What was the role of the first person jailed in the Volkswagen diesel scandal?

The first person jailed for being involded in the VOlkswagen diesel scandal was engineer James Liang.

- What was the problem with a database of suspected gang members maintained by California law enforcement officials?

There was no process in place to remove suspected gang members. The list contained many incorrectly labeled gang members including babies. 

- Why did YouTube's recommendation algorithm recommend videos of partially clothed children to pedophiles, even though no employee at Google had programmed this feature?

YouTube's recommendation algorithm recommended partially clothed children to pedophiles due to feedback loops. Conspiracy videos that users were looking up were also being recommended other videos that conspiracy believers watched which was partially clothed children.

- What are the problems with the centrality of metrics?

When there is a centrality of a metric, the recommendation system will do everything in its power to maximize that number. If not correctly coded, the system may not consider ethical problems and the system could create unintended problems.

- Why did Meetup.com not include gender in its recommendation system for tech meetups?

Meetup.com did not include gender in its recommendation system for tech meetups because the large majority of the attendees were male and therefore, more invites were sent to males creating a dangerous reinforcement loop where less and less women were getting notified about the meetups.

- What are the six types of bias in machine learning, according to Suresh and Guttag?

The six types of bias in machine learning are:
- Historical bias
- Representation bias
- Measurenemtn bias
- Evaluation bias
- Aggregation bias
- Development bias

- Give two examples of historical race bias in the US.
Where are most images in ImageNet from?

Ex 1: Black people being given a starting price tag on a used car that is $700 higher.

Ex 2: An all white jury is 16% higher to convict a black defendant but, if there is one black person on the jury the conviction rates are the same for a white or black defendant.

The majority of ImageNet images are from the US or other western countries.

- In the paper "Does Machine Learning Automate Moral Hazard and Error" why is sinusitis found to be predictive of a stroke?

Sinusitis was found to be a predictive measure of stroke because the model was not measuring just who was increased risk for stroke but also the types of people that actually go to the doctor. This second point has discrimination bias and would effect who might be determined at risk for a stroke.

- What is representation bias?

Representation bias is when a sub-section of a population is under represented in a data set to where the model picks up on this trend and includes it in it's system.

- How are machines and people different, in terms of their use for making decisions?

Machines:
- create feedback loops from a small bias in a data set.
- amplify bias in a data set
- usually don't have an appeals process in place

People: 
- generalize that algorithms are more error-free than they really are
- human bias can lead to larger bias in models

- Is disinformation the same as "fake news"?

No, disinformation is different in that in some cases disinformation can include half truths while 'fake news' is usually just flat out fabricated.

- Why is disinformation through auto-generated text a particularly significant issue?

Disinformation created through auto-generated text is significant because it can be scaled very quickly and people are heavily influenced by people around us.

- What are the five ethical lenses described by the Markkula Center?

The five ethical lenses described by Markkula Center are:
 - rights approach: which option best respects the rights of all people who have a stake?
 - justice approach: which option treats people the most fair?
 - utilitiarian approach: which option will produce the most good and do the least amount of harm?
 - common good approach: which option best serves the community as a whole, and not just the creators?
 - virtue approach: which option leads me to act as the person who I want to be?


- Where is policy an appropriate tool for addressing data ethics issues?

Policy is an appropriate tool for addressing data ethics in companies. If tech companies deploying these models hae a data ethics policy in place, they are much more likely to adhere to it and do less harm.


# Ch 4 Questions

- How is a grayscale image represented on a computer? How about a color image?

Grayscale images are represented by pixels in the range of 0-255. 0 being white and 255 being black. A color image is broken down to pixels and then into bits based on the color depth (how many bits make up each pixel).

- How are the files and folders in the MNIST_SAMPLE dataset structured? Why?

The folders in the MNIST_SAMPLE dataset is split by training data and testing data as well as the corrosponding labels. Each training/testing folder has a subfolder for each of the numbers (1-9). It is structured this way to avoid confusion and allows for easy testing.

- Explain how the "pixel similarity" approach to classifying digits works.
What is a list comprehension? Create one now that selects odd numbers from a list and doubles them.

"Pixel similarity" is when a set of one number's pixels are averaged to create an "ideal" number. With this "ideal" number you can then test how similar a new image is to the "ideal". A list comprehension is a one line for loop.

In [ ]:
# list comprehension that selects odd numbers from a list and doubles them

a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 323, 197, 1038, 111, 29, 27]

odd_list = [a for a in a_list if a % 2 != 0]
new_list = [a * 2 for a in a_list if a % 2 != 0]

print(a_list)
print(odd_list)
print(new_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 323, 197, 1038, 111, 29, 27]
[1, 3, 5, 7, 9, 323, 197, 111, 29, 27]
[2, 6, 10, 14, 18, 646, 394, 222, 58, 54]


- What is a "rank-3 tensor"?

A rank-3 tensor is a 3D array. A rank-0 tensor is also known as a scaler, a rank-1 tensor is also known as a vector, and a rank-2 tensor is also known as a matrix.

- What is the difference between tensor rank and shape? How do you get the rank from the shape?

A tensors rank is it's number of dimensions where a tensors shape is it how many numbers make up the rows and columns. The length of a tensor is it's rank. 

- What are RMSE and L1 norm?

RMSE is the root mean squared error which is a method of measuring accuracy. L1 norm is the absolute value of differences. 

- How can you apply a calculation on thousands of numbers at once, many thousands of times faster than a Python loop?

You can apply a calculation on thousands of numbers at once by using matrix multiplication.

- Create a 3×3 tensor or array containing the numbers from 1 to 9. Double it. Select the bottom-right four numbers.

In [14]:
# 3x3 array w/ numbers 1-9 
import numpy as np
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array = np.array(data)
print(array)
print (' ')

# array * 2
array_2 = array * 2
print(array_2)
print(' ')

# selecting bottom right 4 numbers
print(array_2[1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
 
[[10 12]
 [16 18]]


- What is broadcasting?

Broadcasting occurs when performing calculations on tensors of different ranks, the tensor with the smaller rank will be expanded to fit the larger tensor.

- Are metrics generally calculated using the training set, or the validation set? Why?

In the validation set because this is data that the model has not seen yet and determines if the model is good at generalizing.

- What is SGD?

SGD stands for stochastic gradient descent that aims to improve its accuracy upon each iteration. The basic steps for SGD are: initialize weights -> predict -> calculate loss -> calculate gradient (how changing the weight would effect the loss) -> change weight -> repeat predict! -> stop

- Why does SGD use mini-batches?

SGD uses mini-batches because calculating gradients over an entire dataset would be computationally heavy, and calculating over just one point wouldn't provide accurate gradients.

- What are the seven steps in SGD for machine learning?

See above!

- How do we initialize the weights in a model?

Initializing weights can be done randomally or by using a pre-trained model.

- What is "loss"?

A value that represents how well or poor a model is doing.

- Why can't we always use a high learning rate?

Using a high learning rate could cause your model's loss to be worse than a small learning rate, and also could cause bounce that will not actually improve the model.

- What is a "gradient"?

The derivitive of the loss with respect to a models parameters.

- Do you need to know how to calculate gradients yourself?

No, we have PyTorch for that.

- Why can't we use accuracy as a loss function?


- Draw the sigmoid function. What is special about its shape?

- What is the difference between a loss function and a metric?

- What is the function to calculate new weights using a learning rate?


- What does the DataLoader class do?

- Write pseudocode showing the basic steps taken in each epoch for SGD.
Create a function that, if passed two arguments \[1,2,3,4]\ and 'abcd', returns \[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]\. What is special about that output data structure?

- What does view do in PyTorch?

- What are the "bias" parameters in a neural network? Why do we need them?
What does the @ operator do in Python?

- What does the backward method do?

- Why do we have to zero the gradients?

- What information do we have to pass to Learner?

- Show Python or pseudocode for the basic steps of a training loop.

- What is "ReLU"? Draw a plot of it for values from -2 to +2.

- What is an "activation function"?

- What's the difference between F.relu and nn.ReLU?

- The universal approximation theorem shows that any function can be approximated as closely as needed using just one nonlinearity. So why do we normally use more?